---
product-name: pas-windows
product-properties:
  .properties.bosh_ssh_enabled:
    value: false
  .properties.kms:
    value: disable
  .properties.smoke_tests_windows:
    value: on_demand
  .properties.system_logging:
    value: disable
  .properties.windows_admin_password:
    value: use_default
network-properties:
  network:
    name: ((vsphere_tas_network))
  other_availability_zones:
    - name: pks-az1
  singleton_availability_zone:
    name: pks-az1
resource-config:
  windows_diego_cell:
    instances: 1
    instance_type:
      id: automatic

# Errands here have been disabled
# to facilitate rapid testing of our tooling.
# In your environments, choose which errands to run
# according to your configuration and needs.
errand-config:
  install-hwc-buildpack:
    post-deploy-state: false
  smoke_tests_windows:
    post-deploy-state: false
