opsman-configuration:
  vsphere:
    vcenter:
      url: ((vcenter_url))
      username: ((vcenter_user.username))
      password: ((vcenter_user.password))
      datastore: LUN01
      datacenter: Datacenter
      resource_pool: /Datacenter/host/Cluster
      insecure: 1
    ssh_public_key: ((vsphere_ssh_key))
    disk_type: thin
    private_ip: 172.16.1.10
    dns: 10.192.2.10
    ntp: 10.192.2.11
    hostname: opsmgr-02.haas-405.pez.pivotal.io
    network: PKS-Infrastructure
    netmask: 255.255.255.0
    gateway: 172.16.1.1
    memory: 9
    cpu: 2
